server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicioUsuarios?createDatabaseIfNotExist=true
    username: root
    password:
    drive: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect